### PR TITLE
Fix doc generation for SSH git clones

### LINKED ISSUE #427: Attempting to generate docs in a git@github.com clone fails
Running `./generate.sh` in `docs/verso/` I got:
```
[...]
✖ [321/554] Running Strata:srcUri.github
error: Could not interpret Git remote uri git@github.com:strata-org/Strata as a Github source repo.
See README on source URIs for more details.
[...]
Some required targets logged failures:
- Strata:srcUri.github
- Strata:srcUri.github
- Strata:srcUri.github
- Strata:srcUri.github
- Strata:srcUri.github
- Strata:srcUri.github
error: build failed
```

I don't even know whether this is a Strata or a Lean problem, but it would be great if documentation could also be generated from such a clone, and not just `https://github.com` ones.

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #427

## Problem

Running `./generate.sh` in `docs/verso/` fails when the repo is cloned via SSH (`git@github.com:strata-org/Strata`) because doc-gen4 only recognizes HTTPS GitHub URLs when constructing source links.

## Solution

The `generate.sh` script now detects SSH-format git remotes and temporarily converts them to HTTPS format before running the doc build. The original remote URL is restored on exit via a shell trap, even if the build fails.

## Testing

The change is a shell script only — the Lean build and existing tests are unaffected.

### CODE REVIEW

File: docs/verso/generate.sh [hunk 1]
```diff
@@ -1,5 +1,14 @@
 set -ex
 
+# Normalize SSH git remote to HTTPS so doc-gen4 can parse it (see #427).
+repo_root=$(git -C "$(dirname "$0")/../.." rev-parse --show-toplevel)
+orig_url=$(git -C "$repo_root" remote get-url origin 2>/dev/null || true)
+if echo "$orig_url" | grep -q '^git@github\.com:'; then
+  https_url=$(echo "$orig_url" | sed 's|^git@github\.com:|https://github.com/|; s|\.git$||')
+  git -C "$repo_root" remote set-url origin "$https_url"
+  trap 'git -C "$repo_root" remote set-url origin "$orig_url"' EXIT
```
Comment (MikaelMayer) [inline docs/verso/generate.sh:9]: 👍 Setting the trap only when the URL is actually changed is a nice touch — avoids a no-op restore on HTTPS clones and makes the intent clear.

Comment (MikaelMayer) [reply docs/verso/generate.sh:9]: Thanks! Exactly the intent — no reason to set up a restore trap if we didn't touch the URL.
